# Generated by Django 5.2.5 on 2025-10-25 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=255)),
                ('jawaban_benar', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('K', 'Perempuan')], default='L', max_length=1)),
                ('tgl_lahir', models.DateField()),
                ('tahun_penerimaan', models.SmallIntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_santri', to='evaluasi.santri')),
            ],
        ),
        migrations.CreateModel(
            name='PilihanJawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=1)),
                ('teks', models.CharField(max_length=255)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan', to='evaluasi.soal')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_santri', models.CharField(max_length=1)),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_santri', to='evaluasi.santri')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jwbn_santri', to='evaluasi.soal')),
            ],
        ),
    ]
