# Generated by Django 5.2.5 on 2025-10-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='santri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_santri', to='evaluasi.santri', unique=True),
        ),
    ]
